server:
  port: 8081
spring:
  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/security101
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: c2VydmVyLWJhY2tlbmQtc2VydmVyLWFzZGZhc2RnZXdya2plbGdhaW9kdS15b295ZW9uLXRhbGtlbi1iYWNrZW5kCg==
  expiration: 120000
  redis:
    host: localhost
    port: 6379
